set_property IOSTANDARD LVCMOS18 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN W11 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN W12 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN F7 [get_ports reset_rtl]
